menu:
- {name: 'Home', url: '/'}
- {name: 'News', url: '/news'}
- {name: 'Papers', url: '/papers'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

social:
- {icon: 'linkedin', link: 'https://linkedin.com/in/timplanken'}
- {icon: 'orcid', academicons: 'yes', link: 'https://orcid.org/0009-0007-1659-9221'}
- {icon: 'researchgate', academicons: 'yes', link: 'https://www.researchgate.net/profile/Tim-Planken'}
- {icon: 'google-scholar', academicons: 'yes', link: 'https://scholar.google.com/citations?user=y5JLxjoAAAAJ'}

contacts:
- {name: 'Tim Planken',
   title: 'PhD Student',
   department: 'Faculty of Mathematics and Computer Science',
   institution: 'TU Bergakademie Freiberg',
   email: 'tim.planken at math.tu-freiberg.de',
   office: 'Prüferstraße 1, Zimmer 1.06',
   image: 'assets/img/profile.jpeg'
  }
